### ISSUE TITLE
Github page

### ISSUE THREAD

**Issue by jenkin** [italia/daf-d3-miur-studenti-ateneo#5]
It's a pure client application, so you can activate a github page to show it to everyone.

**Comment by ruphy** [comment]
Live on https://italia.github.io/daf-d3-miur-studenti-ateneo/

**Comment by jenkin** [comment]
Se non funziona, bisogna abilitare il caricamento degli script non sicuri (perché non serviti sotto https), in chrome come da screenshot allegato.

![scrnsht1](https://user-images.githubusercontent.com/426495/35096795-ce58415a-fc4d-11e7-9b11-43f1ca957333.png)
